### ISSUE TITLE
Set up Vagrant Dev Environment

### ISSUE THREAD

**Issue by evpoe** [NYU-DevOps-Suppliers-Team/suppliers#1]
**As a** developer
**I need** a Vagrant development environment
**So that** I have a shared location in which to run code and test application functionality with my team

**Assumptions:**
* We are starting a new project and don't currently have a dev environment
* All developers will clone the same project with a Vagrant config file

**Acceptance Criteria:**
```
Given the Vagrant file is setup
When I do a Vagrant Up and vagrant shh
Then the VM will be brought up without any errors
```

**Comment by beafus** [comment]
Pull request: https://github.com/NYU-DevOps-Suppliers-Team/suppliers/pull/15
