### ISSUE TITLE
CRUD: Delete a Supplier

### ISSUE THREAD

**Issue by CatherineRH** [NYU-DevOps-Suppliers-Team/suppliers#10]
**As a** E-Commerce Manager
**I need** to be able to delete a supplier from the supplier list
**So that** data is accurate/complete

**Assumptions:**
* Deleting and deactivating a supplier are not the same
* Deletions may be applied to erroneous  supplier entries

**Acceptance Criteria:**
```
When I issue a DELETE
AND specify the supplier identifier
The supplier is removed from the supplier list
and the service returns a 204 message + empty body

```

**Comment by CatherineRH** [comment]
@beafus thanks for the clarification on the delete

**Comment by evpoe** [comment]
PR: https://github.com/NYU-DevOps-Suppliers-Team/suppliers/issues/22
