### ISSUE TITLE
Create a skeleton app

### ISSUE THREAD

**Issue by beafus** [NYU-DevOps-Suppliers-Team/suppliers#12]
**As a** Developer
**I need** a starter project with skeleton code
**So that** I can focus on adding new functionality

**Assumptions:**
* Need a skeleton service
* Need skeleton test cases

**Acceptance Criteria:**
```
Given I have a skeleton project
When I clone the project
Then I will have a starting point that already runs and pasts tests
```

**Comment by sa3613** [comment]
@beafus , this is the step we are going to do in pre programming all together correct?

**Comment by beafus** [comment]
Pull request: https://github.com/NYU-DevOps-Suppliers-Team/suppliers/pull/17
