### ISSUE TITLE
Create the supplier data model

### ISSUE THREAD

**Issue by evpoe** [NYU-DevOps-Suppliers-Team/suppliers#14]
**As a** developer
**I need** to store information about suppliers in a database
**So that** I have a place to track supplier details with persistence across multiple sessions/users

**Assumptions:**
Suppliers will have the following attributes
* id
* name
* email
* address
* phone_number (optional)

**Acceptance Criteria:**
```
Given there is no model
When the model is completed
Then there will be a table in the database representing the model
```

**Comment by evpoe** [comment]
Pull request: https://github.com/NYU-DevOps-Suppliers-Team/suppliers/issues/18

**Comment by sa3613** [comment]
Checked the changes, successfully ran nosetests, all good you're awesome
