### ISSUE TITLE
Update Supplier Database Model to Incorporate Product ID

### ISSUE THREAD

**Issue by CatherineRH** [NYU-DevOps-Suppliers-Team/suppliers#20]
**As a** developer
**I need** to store information about suppliers in a database that includes a product ID
**So that** i can call the product service to supply product details as a subordinate REST API

**Assumptions:**
* Product list and detail is maintained by the product team
* Database Model Components 
* supplier id
* name
* email
* address
* phone_number (optional)
* Product ID(s) affiliated with Supplier

**Acceptance Criteria:**
```
Given there is no model
When the model is completed
Then there will be a table in the database representing the model
```

**Comment by evpoe** [comment]
Code looks good and all tests still pass

**Comment by CatherineRH** [comment]
@evpoe I take it this worked out ok when you ran tests again on your end?

**Comment by evpoe** [comment]
@CatherineRH Yes! Sorry I only left a comment on the PR originally
