### ISSUE TITLE
Supplemental Model tests

### ISSUE THREAD

**Issue by CatherineRH** [NYU-DevOps-Suppliers-Team/suppliers#26]
**As a** Developer
**I need** to confirm that the serialize/deserialize functions are working in the model
**So that** I can identify flaws in our microservice

**Assumptions:**
*The lab-flask-rest demo has sufficient serialize/deserialize model tests

**Acceptance Criteria:**
```
When I run nosetests after adding serialize and deserialize test cases into the model.tests file
No errors are returned
```

**Comment by evpoe** [comment]
PR tested and merged!
