### ISSUE TITLE
Add Query Capability to List Route

### ISSUE THREAD

**Issue by CatherineRH** [NYU-DevOps-Suppliers-Team/suppliers#32]
**As a** e-commerce manager
**I need** see a specific subset of suppliers
**So that** I can more efficiently review information I need by name, email, or address rather than reviewing the whole list

**Assumptions:**
* Query suppliers by name to identify and provide data on supplier
* Query suppliers by email to identify and provide data on supplier
* Query suppliers by address to identify and provide data on supplier

**Acceptance Criteria:**
```
WHEN I issue a GET command
AND I specify query criteria
I am returned a 200 message and a list of suppliers specific to query criteria associated supplier qualities (name, unique identifier, etc)
```

**Comment by CatherineRH** [comment]
E.g. query product name, and return supplier ids 1 and 3 in data model

**Comment by evpoe** [comment]
Reviewed and merged code enhancements to add query functionality to our list route.
