### ISSUE TITLE
Travis Automated Test Badge for READ ME

### ISSUE THREAD

**Issue by CatherineRH** [NYU-DevOps-Suppliers-Team/suppliers#34]
**As a** developer
**I need** a Travis badge in the README file
**So that** I and other developers will know if there are broken code elements

**Assumptions:**
* N/A

**Acceptance Criteria:**
```
WHEN I open the README file
AND there is a failing test in the code of the repo
The Travis badge will change to indicate so
```

**Comment by beafus** [comment]
This task has been done in the following PR: https://github.com/NYU-DevOps-Suppliers-Team/suppliers/pull/47
