### ISSUE TITLE
Create ProductList Data Model

### ISSUE THREAD

**Issue by CatherineRH** [NYU-DevOps-Suppliers-Team/suppliers#38]
**As a** developer
**I need** to store information about products provided by suppliers in a database
**So that** I have a place to track product details associated with supplier (associated with supplier id as a foreign key) with persistence across multiple sessions/users

**Assumptions:**
Products will have the following attributes
* id
* name

These will be connected to suppliers via an Association table that includes a wholesale_price

**Acceptance Criteria:**
```
Given there is no model
When the model is completed
Then there will be a table in the database representing the model, which can be tied to the supplier table
```

**Comment by evpoe** [comment]
@beafus Updated with some of the changes you suggested and added test cases. Ready for another review.
