### ISSUE TITLE
CRUD: Add to Product (aka Create)

### ISSUE THREAD

**Issue by sa3613** [NYU-DevOps-Suppliers-Team/suppliers#39]
As an E-commerce Manager
I need to be able to CREATE/ADD a product to my product list
So that I can know which suppliers provide each product and see product details

**Assumptions:**
* New product will need to be added
* Relevant unique identifiers and supplied product details will be available (product name, unique identifier, product price, TBD)
* Data for each product will be maintained by the Product team

**Acceptance Criteria:**
```
When I use POST to create a new product in the product list
A New product resource will be added
AND the Response should be 201 and contain an entity which describes the status of the request and refers to the new resource, and a location header for GET
```

**Comment by CatherineRH** [comment]
@beafus @cambriaso @sa3613 open to some paired programming on this if anyone wants to join
