### ISSUE TITLE
CRUD: Delete from Product

### ISSUE THREAD

**Issue by cambriaso** [NYU-DevOps-Suppliers-Team/suppliers#41]
As a E-Commerce Manager
I need to be able to delete a product from the product list
So that data is accurate/complete

Assumptions:

Deleting and deactivating a product are not the same
Deletions may be applied to erroneous product entries
Acceptance Criteria:

When I issue a DELETE
AND specify the product identifier
The product is removed from the product list
and the service returns a 204 message + empty body

**Comment by evpoe** [comment]
We may not need to build out all the routes for products so please don't start work on this story yet...recommending we focus on associations next.
