### ISSUE TITLE
CRUD: List products 

### ISSUE THREAD

**Issue by cambriaso** [NYU-DevOps-Suppliers-Team/suppliers#43]
As a E-commerce Manager
I need to see a list all product
So that I can clearly identify the supplied products to the business

Assumptions:

There are multiple product
Products may be current or non-current 
Relevant product identifiers are TBD (e.g. Unique ID)

Acceptance Criteria:

When I issue a GET command
AND I specify the PRODUCT bucket
I am returned a 200 message and a complete list of product with all associated product qualities (name, unique identifier, etc)

**Comment by evpoe** [comment]
We may not need to build out all the routes for products so please don't start work on this story yet...recommending we focus on associations next.
