### ISSUE TITLE
Update supplier create service with correct location header

### ISSUE THREAD

**Issue by evpoe** [NYU-DevOps-Suppliers-Team/suppliers#45]
**As an** e-commerce manager
**I need** the API create service to send back the proper location header
**So that** the correct information comes back to the sender

**Assumptions:**
* Production database will also be updated during this story to move from SQLLite to Postgres

**Acceptance Criteria:**
```
Given the updates have been applied
When I call the create service
Then the appropriate location header will be returned
```

**Comment by evpoe** [comment]
JR's comments:

"Create does not send back proper location header (you forgot to uncomment the URL after get_supplier was implemented). Just FYI, your production database is using SQLLite instead of Postgres. You should change the DATABASE_URI in config.py to match the one in your test cases (no points off fo that). 

Otherwise really well done!"

**Comment by CatherineRH** [comment]
Copy and paste from lab-flask-rest

**Comment by evpoe** [comment]
Tested and merged!
