### ISSUE TITLE
CRUD: Create a Supplier-Product Association

### ISSUE THREAD

**Issue by CatherineRH** [NYU-DevOps-Suppliers-Team/suppliers#52]
**As a** E-commerce Manager
**I need** to be able to CREATE/ADD a supplier/product association to the association table
**So that**I can maintain current data in my supplier list

**Assumptions:**
* TBD

**Acceptance Criteria:**
```
When I use POST to create a new association to "/suppliers/{id}/products/{id}"
A new association will be added
AND the Response should be 201 and contain an entity which describes the status of the request and refers to the new resource, and a location header for GET
```

**Comment by evpoe** [comment]
Updated the acceptance criteria
