### ISSUE TITLE
CRUD: Read details about a Supplier-Product Association

### ISSUE THREAD

**Issue by CatherineRH** [NYU-DevOps-Suppliers-Team/suppliers#54]
**As a** E-Commerce manager
**I need** to read data from the association table
**So that** I can make business decisions around products supplied by current and past suppliers

**Assumptions:**
* TBD

**Acceptance Criteria:**
```
When I issue a GET to "/supplier/{id}/products/{id}"
service returns an association relevant information about supplier (name) and the desired product (e.g., name, wholesale_price) 
```

**Comment by evpoe** [comment]
Updated acceptance criteria
