### ISSUE TITLE
CRUD: List all Product Associations from a specified Supplier

### ISSUE THREAD

**Issue by CatherineRH** [NYU-DevOps-Suppliers-Team/suppliers#55]
**As a** E-commerce Manager
**I need** to see a list of all associations for a specific supplier
**So that** I can clearly identify who is supplying and has supplied products to the business

**Assumptions:**
* There are multiple vendors/suppliers
* Suppliers may be current or non-current vendors
* Relevant supplier identifiers are TBD (e.g. Unique ID)

**Acceptance Criteria:**
```
When I issue a GET command to "/supplier/{id}/products"
I am returned a 200 message and a complete list of products associated with that supplier
```

**Comment by evpoe** [comment]
Updated story and acceptance criteria

**Comment by evpoe** [comment]
Reviewed and merged. Looks good.
