### ISSUE TITLE
CRUD: Update Association

### ISSUE THREAD

**Issue by CatherineRH** [NYU-DevOps-Suppliers-Team/suppliers#56]
**As a** E-commerce manager
**I need** to update details (i.e., wholesale_price) about an association
**So that** I can maintain accurate records of supplier

**Assumptions:**
* Relevant details to update are TBD (name, address, etc)

**Acceptance Criteria:**
```
WHEN I issue a PUT to "/supplier/{id}/products/{id}"
"wholesale_price" will be updated in the association table as desire
AND a 200 response will confirm that the list was updated 
```

**Comment by evpoe** [comment]
Updated story and acceptance criteria....wholesale_price is the only column we would ever try to "update" in our associations table
