### ISSUE TITLE
Add Honcho

### ISSUE THREAD

**Issue by CatherineRH** [NYU-DevOps-Suppliers-Team/suppliers#67]
**As a** Developer
**I need** Honcho added to my requirements.txt file and to push the application to the IBM Cloud
**So that** Honcho can manage all of the processes defined within the  Procfile and application is fully deployed

**Assumptions:**
*IBM Cloud Foundry has been used

**Acceptance Criteria:**
```
WHEN I input "honcho start" into the command line
AND I enter CF push into command line
THEN Honcho manages all of the processes defined within the  Procfile and the site URL shows the working microservice
```

**Comment by evpoe** [comment]
This was completed in pull request #44
