### ISSUE TITLE
Create BDD file and associated Steps File

### ISSUE THREAD

**Issue by CatherineRH** [NYU-DevOps-Suppliers-Team/suppliers#68]
**As a** developer
**I need** to be able to test our API from the outside in for all 7 scenarios (e.g., CRUD, etc)
**So that** my microservice is confirmed to behave as expected

**Assumptions:**
* The Gherkin syntax will be used for the feature

**Acceptance Criteria:**
```
GIVEN the feature and step file have been deployed
WHEN I run behave
THEN all test scenarios are green (passing)
```

**Comment by evpoe** [comment]
Reconfiguring BDD issues
