### ISSUE TITLE
Flask-RESTPlus Implementation 

### ISSUE THREAD

**Issue by cambriaso** [NYU-DevOps-Suppliers-Team/suppliers#71]
**As a** developer 
**I need** to refactor my code 
**So that** my microservice follows Flask-RESTPlus implementation 

**Assumptions:**
* the code has passed all tests 

**Acceptance Criteria:**
``` 
GIVEN the new code is refactored following the FlaskRESTPLUS implementation 
WHEN I push new code to production
THEN my tests pass 
AND all errors return Json messages instead of HTML
AND bad data does not result in a 500 type error message
```

**Comment by evpoe** [comment]
This is only necessary if we decided to do swagger documentation

**Comment by beafus** [comment]
Not implemented
