### ISSUE TITLE
BDD Test - Create Supplier

### ISSUE THREAD

**Issue by evpoe** [NYU-DevOps-Suppliers-Team/suppliers#76]
**As a** developer
**I need** I need to test the ability to for a user to create a supplier
**So that** I can ensure our user interface works as intended

**Assumptions:**
* A simple UI has been developed

**Acceptance Criteria:**
```
GIVEN the BDD test for CREATE is in place
WHEN I run "Behave"
THEN the CREATE BDD test execute successfully.
```

**Comment by sa3613** [comment]
able to run behave command and passed all steps in scenario
