### ISSUE TITLE
CRUD: Create a Supplier

### ISSUE THREAD

**Issue by CatherineRH** [NYU-DevOps-Suppliers-Team/suppliers#8]
**As a** E-commerce Manager
**I need** to be able to CREATE/ADD a supplier to my suppliers list
**So that**I can maintain current data in my supplier list

**Assumptions:**
* New suppliers will need to be added
* Relevant unique identifiers and supplied product details will be available (supplier name, unique identifier, supplier address, TBD)
* Product data for each supplier will be maintained by the Product team

**Acceptance Criteria:**
```
When I use POST to create a new supplier in the supplier list
A New Supplier resource will be added
AND the Response should be 201 and contain an entity which describes the status of the request and refers to the new resource, and a location header for GET
```

**Comment by cambriaso** [comment]
PR: https://github.com/NYU-DevOps-Suppliers-Team/suppliers/pull/19

**Comment by evpoe** [comment]
Great work!
